### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by tony13tv** [juanpasolano/sails-hook-cms#2]
It seems that the module `q` its missing from the project. Also it seems to be missing the `require` in the file `jade_helpers.js` (I know it because I already fixed it in my project).

``` bash
/home/cristian/IdeaProjects/sails+backbone/node_modules/sails-hook-cms/node_modules/jade-async/node_modules/promise/node_modules/asap/asap.js:45
                throw e;
                      ^
ReferenceError: Promise is not defined
  at Object.form.getElement (/home/cristian/IdeaProjects/sails+backbone/node_modules/sails-hook-cms/jade-helpers.js:93:19)
  at eval (<anonymous>:2:881)
  at $b4 (<anonymous>:2:937)
  at /home/cristian/IdeaProjects/sails+backbone/node_modules/sails-hook-cms/node_modules/jade-async/lib/runtime.js:195:33
  at /home/cristian/IdeaProjects/sails+backbone/node_modules/sails-hook-cms/node_modules/jade-async/node_modules/promise/index.js:18:19
  at flush (/home/cristian/IdeaProjects/sails+backbone/node_modules/sails-hook-cms/node_modules/jade-async/node_modules/promise/node_modules/asap/asap.js:27:13)
  at process._tickDomainCallback (node.js:459:13)
```

**Comment by juanpasolano** [comment]
Thank you for pointing it out.
I will check it out. Happy New Year

**Comment by juanpasolano** [comment]
So I have looked at your issue and what could be happening is that your version of node does not include the native Promise.
Which version of node are you using?

**Comment by juanpasolano** [comment]
I've made a fix to fallback to q which will be available with sails npm pacakges.js
Will close for now. Please reopen if problem persists

**Comment by Seafnox** [comment]
when last time build a new project grand some error, but "ReferenceError: q is not defined"

fix it by installing q module into project, but error still exsist
